from snakemake.utils import min_version

min_version("6.3.0")

configfile: "config/config.yaml"

include: "rules/generate_proto_primers.smk"
include: "rules/filter_proto_primers_target_species.smk"
include: "rules/main.smk"
include: "rules/utils.smk"