primer_gen_config:
  amplicon_size: 200
  amplicon_buffer_size: 50
  pool_count: 2 # This value does not affect the results and changing it just breaks snakemake. So don't change it.

alignment_settings:
  max_mismatches: 3 # must be between 0 and 3
  # Misalignment score params (incorrect alignments are penalized) 
  alignment_weight: 0.5
  mismatch_weight: 0.5
  base_penalty: 100

# The following primers limit the number of problematic primers
evaluation_settings:
  max_adjacency_limit: 300
  hard_filter: false
  soft_filter_params:
    null # TODO: Placeholder
  hard_filter_params:
    null # TODO: Placeholder