# input files 
reference_genome: "/homes/kkandeepan/Dev/primer-designer/data/myc_tuberculosis_h37Rv.fasta" 
regions: "/homes/kkandeepan/Dev/primer-designer/data/regions.csv" 
index_dir: "/homes/kkandeepan/Dev/primer-designer/data/indexes" 
results_dir: "/homes/kkandeepan/Dev/primer-designer/data/results"
foreign_species_genomes: 
  - "/homes/kkandeepan/Dev/primer-designer/data/foreign_species/GRCh38.fasta"

primer_gen_config:
  min_amplicon_size: 200
  max_amplicon_size: 300
  min_overlap: 0.2 # 20% overlap between primers from different pools

metadata:
  pool_count: 2 # This value does not affect the results and changing it just breaks snakemake. So don't change it.
  species: "myc_tuberculosis_h37Rv"
  chromosome: "NC_000962.3"

alignment_settings:
  max_mismatches: 3 # must be between 0 and 3
  # Misalignment score params (incorrect alignments are penalized) 
  alignment_weight: 0.5
  mismatch_weight: 0.5
  base_penalty: 100

# The following settings filter out misaligned primers and amplicons
evaluation_settings:
  target_filter:
    max_adjacency_limit: 300
    threshold: 0
  foreign_filter:
    max_adjacency_limit: 300
    threshold: 0

saddle:
  min_subsequence_size: 4 # min size of subsequence to be considered for badness
  max_subsequence_size: 8 # max size of subsequence to be considered for badness
  optimal_iterations: 35_000 # optimal number of iterations for simulated annealing
  amplicons_weight: 5.0 # weight of amplicons during simulated annealing temperature calculation
  primers_weight: 10.0 # weight of primers during simulated annealing temperature calculation

plot:
  plotting_buffer: 300