PRIMER_TASK: generic
PRIMER_MIN_SIZE: 18
PRIMER_MAX_SIZE: 25
PRIMER_OPT_TM: 60.0
PRIMER_MIN_TM: 55.0
PRIMER_MAX_TM: 65.0
PRIMER_MIN_GC: 35.0
PRIMER_MAX_GC: 80.0
PRIMER_OPT_SIZE: 20
PRIMER_NUM_RETURN: 10
PRIMER_PRODUCT_SIZE_RANGE: DUMMY  # Note: this value is calculated on the fly and just needs to be present